#parameters:
#  sonata.media.admin.media.class: Application\Sonata\MediaBundle\Admin\MediaAdmin

sonata_media:
    db_driver:       doctrine_orm
    default_context: default
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, quality: 100}
                blog: { width: 215, quality: 100 }
                big:   { width: 640 , quality: 100}


    cdn:
        # define the public base url for the uploaded media
        server:
            path:      %sonata_media.cdn.host%

    filesystem:
        # define where the uploaded file will be stored
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true


    providers:
        image:
          allowed_extensions: ['jpg', 'png', 'gif', 'jpeg', 'tiff']
          allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif', 'image/tiff']
        file:
            resizer:    false

    resizer:
        simple:
#            mode:  outbound
            mode:  inset

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
