sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    templates:
      layout:  SonataAdminBundle::layout.html.twig
        
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
